site_name: Salesforce i NAV
repo_url: https://github.com/navikt/salesforce-i-NAV
edit_uri: edit/main/docs/
nav:
  - Hjem:
    - index.md
  - Arkitektur:
    - 'Konseptuell arkitektur': arkitektur/introduksjon.md
  - Utvikling:
    - utvikling/index.md
    - Kom i gang:
      - 'Oppsett og konfig': utvikling/setup.md
      - 'Ny utvikler': utvikling/ny-utvikler.md
    - DevOps: utvikling/devops.md
    - Felleskomponenter: utvikling/felleskomponenter.md
  
  - Eksempler:
    - 'Introduksjon': eksempler/introduksjon.md 
  - Historikk:
    - 'Innledning': historikk/innledning.md 
  - Ressurser:
    - 'Ressurser': ressurser/introduksjon.md 

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.expand
  icon:
    repo: fontawesome/brands/github
  palette: 
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  markdown_extensions:
    - def_list
    - attr_list
    - md_in_html
    - pymdownx.highlight:
        anchor_linenums: true
    
  
  