site_name: Salesforce i NAV
repo_url: https://github.com/navikt/salesforce-i-NAV
edit_uri: edit/main/docs/
theme:
  name: material
  language: 'en'
  favicon: assets/logo.png
  custom_dir: custom_theme_overrides
  palette:
    scheme: slate
    primary: light blue
    accent: light blue
  features:
    - content.code.copy
    - content.code.annotate
    - navigation.instant
    - navigation.tabs
extra:
  search:
    language: 'en'
extra_css:
  - material_theme_stylesheet_overrides/sf.css
plugins:
  - search
markdown_extensions:
  - toc:
      permalink: True
  - admonition
  - pymdownx.details
  - pymdownx.caret
  - pymdownx.tilde
  - pymdownx.superfences:
      preserve_tabs: true
  - pymdownx.highlight:
      css_class: codehilite
      linenums_style: pymdownx-inline
  - pymdownx.tasklist
  - pymdownx.smartsymbols
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
nav:
  - SF Development:
    - Introduction to SF: README.md
    - Getting started:
      - Access from laptop: getting_started/access.md
      - Teams: getting_started/teams.md
      - Your first Salesforce application: getting_started/application.md
    - Development:
      - Full example: development/example.md
      - Reference: development/application.md
      - Access policy: development/access-policy.md
      - Automatic scaling: development/automatic-scaling.md
      - Config: development/config-reloading.md
      - Good practices: development/good-practices.md
      - Debugging: development/debugging.md
    - Deploy:
      - SF deploy: deploy/intro.md
      - Changing teams: deploy/change-team.md
      - Delete app: deploy/delete-app.md
      - Troubleshooting: deploy/troubleshooting.md
      - Manual deploy: deploy/manual.md
    - Monitoring:
      - Alerts:
        - Alerts Overview: monitoring/alerts/readme.md
        - Full example: monitoring/alerts/example.md
        - Recommended: monitoring/alerts/recommended_alerts.md
        - Reference: monitoring/alerts/reference.md
      - Logs:
        - Logs Overview: monitoring/logs/readme.md
        - Examples: monitoring/logs/examples.md
      - Metrics: monitoring/metrics.md
      - Tracing: monitoring/tracing.md
    - Integration:
      - Kafka: 
        - Introduction: integration/kafka/intro.md
        - Getting started: integration/kafka/getting_started.md
    - Security:
      - Auth:
        - Introduction: security/auth/intro.md
        - Getting started: security/auth/getting_started.md
    - Addons:
      - Addon test: addons/addon_test.md
    - Support: support.md
  - SF Design:
    - Introduction to design with Salesforce: README_DESIGN.md
  - SF Business:
    - Business thinking with Salesforce: README_BUSINESS.md
  - FAQ:
    - Frequntly asked questions: faq.md